import { registerComponentEditor } from "../ComponentEditors";
import AnimatedModelComponent from "./AnimatedModelComponent";
import AnimatedModelComponentEditor from "./AnimatedModelComponent.editor";
registerComponentEditor(AnimatedModelComponent, AnimatedModelComponentEditor);
import BufferGeometryComponent from "./BufferGeometryComponent";
import BufferGeometryComponentEditor from "./BufferGeometryComponent.editor";
registerComponentEditor(BufferGeometryComponent, BufferGeometryComponentEditor);
import CameraComponent from "./CameraComponent";
import CameraComponentEditor from "./CameraComponent.editor";
registerComponentEditor(CameraComponent, CameraComponentEditor);
import DataComponent from "./DataComponent";
import DataComponentEditor from "./DataComponent.editor";
registerComponentEditor(DataComponent, DataComponentEditor);
import DirectionalLightComponent from "./DirectionalLightComponent";
import DirectionalLightComponentEditor from "./DirectionalLightComponent.editor";
registerComponentEditor(DirectionalLightComponent, DirectionalLightComponentEditor);
import GeometryComponent from "./GeometryComponent";
import GeometryComponentEditor from "./GeometryComponent.editor";
registerComponentEditor(GeometryComponent, GeometryComponentEditor);
import HemisphereLightComponent from "./HemisphereLightComponent";
import HemisphereLightComponentEditor from "./HemisphereLightComponent.editor";
registerComponentEditor(HemisphereLightComponent, HemisphereLightComponentEditor);
import MaterialComponent from "./MaterialComponent";
import MaterialComponentEditor from "./MaterialComponent.editor";
registerComponentEditor(MaterialComponent, MaterialComponentEditor);
import MeshComponent from "./MeshComponent";
import MeshComponentEditor from "./MeshComponent.editor";
registerComponentEditor(MeshComponent, MeshComponentEditor);
import ModelComponent from "./ModelComponent";
import ModelComponentEditor from "./ModelComponent.editor";
registerComponentEditor(ModelComponent, ModelComponentEditor);
import PointLightComponent from "./PointLightComponent";
import PointLightComponentEditor from "./PointLightComponent.editor";
registerComponentEditor(PointLightComponent, PointLightComponentEditor);
import PrefabRefComponent from "./PrefabRefComponent";
import PrefabRefComponentEditor from "./PrefabRefComponent.editor";
registerComponentEditor(PrefabRefComponent, PrefabRefComponentEditor);
import SoundComponent from "./SoundComponent";
import SoundComponentEditor from "./SoundComponent.editor";
registerComponentEditor(SoundComponent, SoundComponentEditor);
import SpotLightComponent from "./SpotLightComponent";
import SpotLightComponentEditor from "./SpotLightComponent.editor";
registerComponentEditor(SpotLightComponent, SpotLightComponentEditor);
import SpriteComponent from "./SpriteComponent";
import SpriteComponentEditor from "./SpriteComponent.editor";
registerComponentEditor(SpriteComponent, SpriteComponentEditor);
import TextComponent from "./TextComponent";
import TextComponentEditor from "./TextComponent.editor";
registerComponentEditor(TextComponent, TextComponentEditor);
