import { registerComponentEditor } from "../ComponentEditors";
import AnimatedModelComponent from "../../runtime/components/AnimatedModelComponent";
import AnimatedModelComponentEditor from "./AnimatedModelComponent.editor";
registerComponentEditor(AnimatedModelComponent, AnimatedModelComponentEditor);
import BufferGeometryComponent from "../../runtime/components/BufferGeometryComponent";
import BufferGeometryComponentEditor from "./BufferGeometryComponent.editor";
registerComponentEditor(BufferGeometryComponent, BufferGeometryComponentEditor);
import CameraComponent from "../../runtime/components/CameraComponent";
import CameraComponentEditor from "./CameraComponent.editor";
registerComponentEditor(CameraComponent, CameraComponentEditor);
import DataComponent from "../../runtime/components/DataComponent";
import DataComponentEditor from "./DataComponent.editor";
registerComponentEditor(DataComponent, DataComponentEditor);
import DirectionalLightComponent from "../../runtime/components/DirectionalLightComponent";
import DirectionalLightComponentEditor from "./DirectionalLightComponent.editor";
registerComponentEditor(DirectionalLightComponent, DirectionalLightComponentEditor);
import GeometryComponent from "../../runtime/components/GeometryComponent";
import GeometryComponentEditor from "./GeometryComponent.editor";
registerComponentEditor(GeometryComponent, GeometryComponentEditor);
import HemisphereLightComponent from "../../runtime/components/HemisphereLightComponent";
import HemisphereLightComponentEditor from "./HemisphereLightComponent.editor";
registerComponentEditor(HemisphereLightComponent, HemisphereLightComponentEditor);
import MaterialComponent from "../../runtime/components/MaterialComponent";
import MaterialComponentEditor from "./MaterialComponent.editor";
registerComponentEditor(MaterialComponent, MaterialComponentEditor);
import MeshComponent from "../../runtime/components/MeshComponent";
import MeshComponentEditor from "./MeshComponent.editor";
registerComponentEditor(MeshComponent, MeshComponentEditor);
import ModelComponent from "../../runtime/components/ModelComponent";
import ModelComponentEditor from "./ModelComponent.editor";
registerComponentEditor(ModelComponent, ModelComponentEditor);
import PointLightComponent from "../../runtime/components/PointLightComponent";
import PointLightComponentEditor from "./PointLightComponent.editor";
registerComponentEditor(PointLightComponent, PointLightComponentEditor);
import PrefabRefComponent from "../../runtime/components/PrefabRefComponent";
import PrefabRefComponentEditor from "./PrefabRefComponent.editor";
registerComponentEditor(PrefabRefComponent, PrefabRefComponentEditor);
import SoundComponent from "../../runtime/components/SoundComponent";
import SoundComponentEditor from "./SoundComponent.editor";
registerComponentEditor(SoundComponent, SoundComponentEditor);
import SpotLightComponent from "../../runtime/components/SpotLightComponent";
import SpotLightComponentEditor from "./SpotLightComponent.editor";
registerComponentEditor(SpotLightComponent, SpotLightComponentEditor);
import SpriteComponent from "../../runtime/components/SpriteComponent";
import SpriteComponentEditor from "./SpriteComponent.editor";
registerComponentEditor(SpriteComponent, SpriteComponentEditor);
import TextComponent from "../../runtime/components/TextComponent";
import TextComponentEditor from "./TextComponent.editor";
registerComponentEditor(TextComponent, TextComponentEditor);
import RuntimeComponent from "../../runtime/components/RuntimeComponent";
import RuntimeComponentEditor from "./RuntimeComponent.editor";
registerComponentEditor(RuntimeComponent, RuntimeComponentEditor);
