import { registerComponentEditor } from "../ComponentEditors.js";
import SkinnedMeshComponent from "../../runtime/components/SkinnedMeshComponent.js";
import SkinnedMeshComponentEditor from "./SkinnedMeshComponent.editor.js";
registerComponentEditor(SkinnedMeshComponent, SkinnedMeshComponentEditor);
import BufferGeometryComponent from "../../runtime/components/BufferGeometryComponent.js";
import BufferGeometryComponentEditor from "./BufferGeometryComponent.editor.js";
registerComponentEditor(BufferGeometryComponent, BufferGeometryComponentEditor);
import CameraComponent from "../../runtime/components/CameraComponent.js";
import CameraComponentEditor from "./CameraComponent.editor.js";
registerComponentEditor(CameraComponent, CameraComponentEditor);
import DataComponent from "../../runtime/components/DataComponent.js";
import DataComponentEditor from "./DataComponent.editor.js";
registerComponentEditor(DataComponent, DataComponentEditor);
import DirectionalLightComponent from "../../runtime/components/DirectionalLightComponent.js";
import DirectionalLightComponentEditor from "./DirectionalLightComponent.editor.js";
registerComponentEditor(DirectionalLightComponent, DirectionalLightComponentEditor);
import GeometryComponent from "../../runtime/components/GeometryComponent.js";
import GeometryComponentEditor from "./GeometryComponent.editor.js";
registerComponentEditor(GeometryComponent, GeometryComponentEditor);
import HemisphereLightComponent from "../../runtime/components/HemisphereLightComponent.js";
import HemisphereLightComponentEditor from "./HemisphereLightComponent.editor.js";
registerComponentEditor(HemisphereLightComponent, HemisphereLightComponentEditor);
import MaterialComponent from "../../runtime/components/MaterialComponent.js";
import MaterialComponentEditor from "./MaterialComponent.editor.js";
registerComponentEditor(MaterialComponent, MaterialComponentEditor);
import ModelComponent from "../../runtime/components/ModelComponent.js";
import ModelComponentEditor from "./ModelComponent.editor.js";
registerComponentEditor(ModelComponent, ModelComponentEditor);
import PointLightComponent from "../../runtime/components/PointLightComponent.js";
import PointLightComponentEditor from "./PointLightComponent.editor.js";
registerComponentEditor(PointLightComponent, PointLightComponentEditor);
import PrefabRefComponent from "../../runtime/components/PrefabRefComponent.js";
import PrefabRefComponentEditor from "./PrefabRefComponent.editor.js";
registerComponentEditor(PrefabRefComponent, PrefabRefComponentEditor);
import SoundComponent from "../../runtime/components/SoundComponent.js";
import SoundComponentEditor from "./SoundComponent.editor.js";
registerComponentEditor(SoundComponent, SoundComponentEditor);
import SpotLightComponent from "../../runtime/components/SpotLightComponent.js";
import SpotLightComponentEditor from "./SpotLightComponent.editor.js";
registerComponentEditor(SpotLightComponent, SpotLightComponentEditor);
import SpriteComponent from "../../runtime/components/SpriteComponent.js";
import SpriteComponentEditor from "./SpriteComponent.editor.js";
registerComponentEditor(SpriteComponent, SpriteComponentEditor);
import TextComponent from "../../runtime/components/TextComponent.js";
import TextComponentEditor from "./TextComponent.editor.js";
registerComponentEditor(TextComponent, TextComponentEditor);
import RuntimeComponent from "../../runtime/components/RuntimeComponent.js";
import RuntimeComponentEditor from "./RuntimeComponent.editor.js";
registerComponentEditor(RuntimeComponent, RuntimeComponentEditor);
